Update android.yml

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -1,4 +1,4 @@
-name: Build TikTok Offline
+name: Build TikTok Offline APK
 
 on:
   workflow_dispatch:
@@ -50,15 +50,14 @@ jobs:
             | head -n 1)
 
           if [ -z "$SETTINGS" ]; then
-            echo "ERROR: settings.gradle.kts tidak ditemukan!"
-            find project -maxdepth 5 -print
+            echo "ERROR: settings.gradle tidak ditemukan!"
             exit 1
           fi
 
           PROJECT_DIR=$(dirname "$SETTINGS")
 
-          echo "Project:"
-          echo "$PROJECT_DIR"
+          echo "=== Project ==="
+          ls -la "$PROJECT_DIR"
 
           echo "project_dir=$PROJECT_DIR" >> "$GITHUB_OUTPUT"
 
@@ -67,22 +66,52 @@ jobs:
         with:
           gradle-version: '9.3.1'
 
+      - name: Create debug keystore
+        working-directory: ${{ steps.find_project.outputs.project_dir }}
+        shell: bash
+        run: |
+          set -e
+
+          echo "=== Checking debug keystore ==="
+          pwd
+          ls -la
+
+          if [ ! -f "debug.keystore" ]; then
+            echo "Creating debug.keystore..."
+
+            keytool -genkeypair \
+              -v \
+              -keystore "debug.keystore" \
+              -alias androiddebugkey \
+              -keyalg RSA \
+              -keysize 2048 \
+              -validity 10000 \
+              -storepass android \
+              -keypass android \
+              -dname "CN=Android Debug,O=Android,C=US"
+
+            echo "debug.keystore berhasil dibuat."
+          else
+            echo "debug.keystore sudah ada."
+          fi
+
+          echo "=== Verify ==="
+          ls -lh "debug.keystore"
+
       - name: Build Debug APK
         working-directory: ${{ steps.find_project.outputs.project_dir }}
         shell: bash
         run: |
           set -e
 
-          echo "=== Project ==="
-          ls -la
-
           echo "=== Build APK ==="
+
           gradle assembleDebug --stacktrace
 
       - name: Find APK
         shell: bash
         run: |
-          echo "=== APK ==="
+          echo "=== APK hasil build ==="
           find project -type f -name "*.apk" -print
 
       - name: Upload APK
